version: "3.9"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    networks:
      - postgres-network
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: always
    networks:
      - postgres-network
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - nodejs-postgres:/data/postgres
      - ./postgres/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
      - ./postgres/backup:/backup  # Mapping backup directory
    restart: always
    networks:
      - postgres-network


volumes:
  nodejs-postgres:
networks: 
  postgres-network:
    driver: bridge